{% set name = "pycomm3" %}
{% set version = "1.2.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycomm3-{{ version }}.tar.gz
  sha256: ffabe89cda3df733fc046e261c15d263134f2f35d7dbb6aedf788203a10615b7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pycomm3
    - pycomm3.cip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ottowayi/pycomm3
  summary: A Python Ethernet/IP library for communicating with Allen-Bradley PLCs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
